# Site settings
title: Seasoning Development Blog
email: joep.driesen@seasoning.be
description: > # this means to ignore newlines until "baseurl:"
  A blog containing posts about the problems encountered during the
  development of Seasoning or other projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.seasoning.be" # the base hostname & protocol for your site
twitter_username: SeasoningBe
github_username: SeasoningDev

# Build settings
markdown: kramdown
